set_property SRC_FILE_INFO {cfile:D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/constrs_1/new/board_demo_competition_dac8_top.xdc rfile:../../../interp4_ctrl.srcs/constrs_1/new/board_demo_competition_dac8_top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports sw0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports sw1]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports sw2]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports dac_clk]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {dac_data[0]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {dac_data[1]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {dac_data[2]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {dac_data[3]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {dac_data[4]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {dac_data[5]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {dac_data[6]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {dac_data[7]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group [get_clocks -quiet -of_objects [get_pins u_clk_wiz_audio_44k1/inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -quiet -of_objects [get_pins u_clk_wiz_audio_48k/inst/mmcm_adv_inst/CLKOUT0]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_audio_128x_sel]]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_demo_interp_dac8_mmcm_common/dbg_y4_w[0]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[1]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[2]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[3]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[4]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[5]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[6]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[7]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[8]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[9]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[10]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[11]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[12]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[13]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[14]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[15]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[16]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[17]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[18]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[19]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[20]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[21]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[22]} {u_demo_interp_dac8_mmcm_common/dbg_y4_w[23]}]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_demo_interp_dac8_mmcm_common/rom_addr[0]} {u_demo_interp_dac8_mmcm_common/rom_addr[1]} {u_demo_interp_dac8_mmcm_common/rom_addr[2]} {u_demo_interp_dac8_mmcm_common/rom_addr[3]} {u_demo_interp_dac8_mmcm_common/rom_addr[4]} {u_demo_interp_dac8_mmcm_common/rom_addr[5]}]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_demo_interp_dac8_mmcm_common/dbg_y8_w[0]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[1]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[2]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[3]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[4]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[5]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[6]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[7]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[8]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[9]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[10]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[11]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[12]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[13]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[14]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[15]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[16]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[17]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[18]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[19]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[20]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[21]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[22]} {u_demo_interp_dac8_mmcm_common/dbg_y8_w[23]}]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_demo_interp_dac8_mmcm_common/mode_state[0]} {u_demo_interp_dac8_mmcm_common/mode_state[1]}]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_demo_interp_dac8_mmcm_common/selected_sample[0]} {u_demo_interp_dac8_mmcm_common/selected_sample[1]} {u_demo_interp_dac8_mmcm_common/selected_sample[2]} {u_demo_interp_dac8_mmcm_common/selected_sample[3]} {u_demo_interp_dac8_mmcm_common/selected_sample[4]} {u_demo_interp_dac8_mmcm_common/selected_sample[5]} {u_demo_interp_dac8_mmcm_common/selected_sample[6]} {u_demo_interp_dac8_mmcm_common/selected_sample[7]} {u_demo_interp_dac8_mmcm_common/selected_sample[8]} {u_demo_interp_dac8_mmcm_common/selected_sample[9]} {u_demo_interp_dac8_mmcm_common/selected_sample[10]} {u_demo_interp_dac8_mmcm_common/selected_sample[11]} {u_demo_interp_dac8_mmcm_common/selected_sample[12]} {u_demo_interp_dac8_mmcm_common/selected_sample[13]} {u_demo_interp_dac8_mmcm_common/selected_sample[14]} {u_demo_interp_dac8_mmcm_common/selected_sample[15]} {u_demo_interp_dac8_mmcm_common/selected_sample[16]} {u_demo_interp_dac8_mmcm_common/selected_sample[17]} {u_demo_interp_dac8_mmcm_common/selected_sample[18]} {u_demo_interp_dac8_mmcm_common/selected_sample[19]} {u_demo_interp_dac8_mmcm_common/selected_sample[20]} {u_demo_interp_dac8_mmcm_common/selected_sample[21]} {u_demo_interp_dac8_mmcm_common/selected_sample[22]} {u_demo_interp_dac8_mmcm_common/selected_sample[23]}]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_demo_interp_dac8_mmcm_common/x_in[0]} {u_demo_interp_dac8_mmcm_common/x_in[1]} {u_demo_interp_dac8_mmcm_common/x_in[2]} {u_demo_interp_dac8_mmcm_common/x_in[3]} {u_demo_interp_dac8_mmcm_common/x_in[4]} {u_demo_interp_dac8_mmcm_common/x_in[5]} {u_demo_interp_dac8_mmcm_common/x_in[6]} {u_demo_interp_dac8_mmcm_common/x_in[7]} {u_demo_interp_dac8_mmcm_common/x_in[8]} {u_demo_interp_dac8_mmcm_common/x_in[9]} {u_demo_interp_dac8_mmcm_common/x_in[10]} {u_demo_interp_dac8_mmcm_common/x_in[11]} {u_demo_interp_dac8_mmcm_common/x_in[12]} {u_demo_interp_dac8_mmcm_common/x_in[13]} {u_demo_interp_dac8_mmcm_common/x_in[14]} {u_demo_interp_dac8_mmcm_common/x_in[15]} {u_demo_interp_dac8_mmcm_common/x_in[16]} {u_demo_interp_dac8_mmcm_common/x_in[17]} {u_demo_interp_dac8_mmcm_common/x_in[18]} {u_demo_interp_dac8_mmcm_common/x_in[19]} {u_demo_interp_dac8_mmcm_common/x_in[20]} {u_demo_interp_dac8_mmcm_common/x_in[21]} {u_demo_interp_dac8_mmcm_common/x_in[22]} {u_demo_interp_dac8_mmcm_common/x_in[23]}]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_demo_interp_dac8_mmcm_common/dac_data_r[0]} {u_demo_interp_dac8_mmcm_common/dac_data_r[1]} {u_demo_interp_dac8_mmcm_common/dac_data_r[2]} {u_demo_interp_dac8_mmcm_common/dac_data_r[3]} {u_demo_interp_dac8_mmcm_common/dac_data_r[4]} {u_demo_interp_dac8_mmcm_common/dac_data_r[5]} {u_demo_interp_dac8_mmcm_common/dac_data_r[6]} {u_demo_interp_dac8_mmcm_common/dac_data_r[7]}]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_demo_interp_dac8_mmcm_common/ila_mode_sel_w[0]} {u_demo_interp_dac8_mmcm_common/ila_mode_sel_w[1]}]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_demo_interp_dac8_mmcm_common/sample_u8_w[0]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[1]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[2]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[3]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[4]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[5]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[6]} {u_demo_interp_dac8_mmcm_common/sample_u8_w[7]}]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list u_demo_interp_dac8_mmcm_common/dbg_y4_valid_w]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list u_demo_interp_dac8_mmcm_common/dbg_y8_valid_w]]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list u_demo_interp_dac8_mmcm_common/selected_valid]]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list u_demo_interp_dac8_mmcm_common/x_in_update_ce]]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list u_demo_interp_dac8_mmcm_common/x_in_valid]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_audio_128x_sel]
