# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.cache/wt [current_project]
set_property parent.project_path D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/bridge_to_interp2_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/new/demo_interp_dac8_mmcm_common.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/fir_core_symm_interp2.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/fir_core_synm.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/interp128_top_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/interp2_ctrl_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/interp2_top_symm_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/interp4_ctrl_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/interp4_top_symm_ce.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/imports/new/round_sat_q16_to24.v
  D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/new/board_demo_competition_dac8_top.v
}
read_ip -quiet D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_44k1/clk_wiz_audio_44k1.xci
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_44k1/clk_wiz_audio_44k1_board.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_44k1/clk_wiz_audio_44k1.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_44k1/clk_wiz_audio_44k1_late.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_44k1/clk_wiz_audio_44k1_ooc.xdc]

read_ip -quiet D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xci
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_board.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_late.xdc]
set_property used_in_implementation false [get_files -all d:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/constrs_1/new/board_demo_competition_dac8_top.xdc
set_property used_in_implementation false [get_files D:/FpgaProject/XilinxProject/XC7A35T/fir_interpolation/interp4_ctrl/interp4_ctrl.srcs/constrs_1/new/board_demo_competition_dac8_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top board_demo_competition_dac8_top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board_demo_competition_dac8_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_demo_competition_dac8_top_utilization_synth.rpt -pb board_demo_competition_dac8_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
