# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xci
# IP: The module: 'clk_wiz_audio_48k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xci
# IP: The module: 'clk_wiz_audio_48k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/20260128learn/fpga_class/interp4_ctrl/interp4_ctrl.srcs/sources_1/ip/clk_wiz_audio_48k/clk_wiz_audio_48k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio_48k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
