`timescale 1ns / 1ps

// Fixed-configuration wrapper for the P4-C/P4-D national-finals filter core.
// Regression scale belongs to the testbench and cannot alter this topology.
module nf_signedoff_filter_core (
    input  wire               clk,
    input  wire               rst_n,
    input  wire               ce2_out,
    input  wire               ce4_out,
    input  wire               ce8_out,
    input  wire               ce16_out,
    input  wire               ce32_out,
    input  wire               ce64_out,
    input  wire               ce128_out,
    input  wire signed [23:0] x_in,
    input  wire               x_in_valid,
    output wire signed [23:0] y_out,
    output wire               y_out_valid,
    output wire signed [23:0] dbg_y2,
    output wire               dbg_y2_valid,
    output wire signed [23:0] dbg_y4,
    output wire               dbg_y4_valid,
    output wire signed [23:0] dbg_y8,
    output wire               dbg_y8_valid,
    output wire signed [23:0] dbg_y16,
    output wire               dbg_y16_valid,
    output wire signed [23:0] dbg_y32,
    output wire               dbg_y32_valid,
    output wire signed [23:0] dbg_y64,
    output wire               dbg_y64_valid
);

    interp128_all2x_v7_folded_fir_cic_top_ce #(
        .STAGE1_ACC_W(41),
        .STAGE23_ACC_W(38),
        .CIC_ORDER(3),
        .FINAL_PRUNE_LSB(0),
        .USE_LUTRAM_STAGE23(1),
        .STAGE3_FLAT(1),
        .USE_CIC3_SHIFTADD_COMPENSATOR(1),
        .USE_BRAM_STAGE23_HISTORY(1),
        .USE_UNIFIED_BRAM_STAGE23_HISTORY(1),
        .USE_SINGLE_BRAM_STAGE1(1),
        .USE_BRAM_STAGE23_COEFF(1),
        .USE_PACKED_BRAM_STAGE23(0),
        .CIC_BURST_COUNTER_USE_DSP(0),
        .CIC_COMB_USE_DSP(0),
        .USE_SERIAL_CIC_COMB(1),
        .USE_N3_HOLD_EQUIV(1),
        .USE_STAGE1_DSP48_PREADDER(1),
        .USE_NATIONAL_FINALS_NARROW_STAGE23(1),
        .ASSUME_ALIGNED_POW2_CE(1),
        .CIC_INTEGRATOR_DSP_MODE(2),
        .USE_SHARED_PCM_STAGE1_BRAM(1),
        .USE_UNIFIED_FIR_COEFF_BRAM(1)
    ) u_signedoff_core (
        .clk(clk),
        .rst_n(rst_n),
        .ce2_out(ce2_out),
        .ce4_out(ce4_out),
        .ce8_out(ce8_out),
        .ce16_out(ce16_out),
        .ce32_out(ce32_out),
        .ce64_out(ce64_out),
        .ce128_out(ce128_out),
        .x_in(x_in),
        .x_in_valid(x_in_valid),
        .pcm_sample_ce(1'b0),
        .pcm_family_48k(1'b0),
        .pcm_sample_out(),
        .pcm_sample_update(),
        .pcm_sample_addr_dbg(),
        .pcm_deadline_miss_dbg(),
        .y_out(y_out),
        .y_out_valid(y_out_valid),
        .dbg_y2(dbg_y2),
        .dbg_y2_valid(dbg_y2_valid),
        .dbg_y4(dbg_y4),
        .dbg_y4_valid(dbg_y4_valid),
        .dbg_y8(dbg_y8),
        .dbg_y8_valid(dbg_y8_valid),
        .dbg_y16(dbg_y16),
        .dbg_y16_valid(dbg_y16_valid),
        .dbg_y32(dbg_y32),
        .dbg_y32_valid(dbg_y32_valid),
        .dbg_y64(dbg_y64),
        .dbg_y64_valid(dbg_y64_valid)
    );

endmodule
